spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://USERSERVICE
          predicates:
            - Path=/user/**
          filters:
            - CustomJWTFilter
        - id: order-service
          uri: lb://ORDERSERVICE
          predicates:
            - Path=/order/**, /cart/**
          filters:
            - CustomJWTFilter
            - name: CircuitBreaker
              args:
                name: orderCircuitBreaker
                fallbackUri: forward:/exception/order
        - id: auth-service
          uri: lb://AUTHRIZATIONSERVER
          predicates:
            - Path=/auth/**

resilience4j:
  circuitbreaker:
    instances:
      orderCircuitBreaker:
        registerHealthIndicator: true
        permittedNumberOfCallsInHalfOpenState: 3
        failureRateThreshold: 50
        waitDurationInOpenState: 30s
        automaticTransitionFromOpenToHalfOpenEnabled: true
        slidingWindowSize: 10
        slidingWindowType: TIME_BASED


eureka:
  client:
    serviceUrl:
      defaultZone:  ${EUREKA_URI:http://localhost:8761/eureka}


logging:
  level:
    com.eshopping.apigateway: DEBUG
  pattern:
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"

server:
  port: 9000